#include <windows.h>
DECLSPEC_IMPORT BOOL WINAPI KERNEL32$SetFileTime(HANDLE, const FILETIME*, const FILETIME*, const FILETIME*);
DECLSPEC_IMPORT HANDLE WINAPI KERNEL32$CreateFileA(LPCSTR, DWORD, DWORD, LPSECURITY_ATTRIBUTES, DWORD, DWORD, HANDLE);
DECLSPEC_IMPORT BOOL WINAPI KERNEL32$CloseHandle(HANDLE);
DECLSPEC_IMPORT BOOL WINAPI KERNEL32$GetFileTime(HANDLE, LPFILETIME, LPFILETIME, LPFILETIME);
DECLSPEC_IMPORT _CRTIMP int __cdecl MSVCRT$sscanf_s(const char *_Src,const char *_Format,...);
DECLSPEC_IMPORT WINBOOL WINAPI KERNEL32$SystemTimeToFileTime(CONST SYSTEMTIME *lpSystemTime, LPFILETIME lpFileTime);
DECLSPEC_IMPORT DWORD WINAPI KERNEL32$GetLastError();

#define SetFileTime KERNEL32$SetFileTime
#define CreateFileA KERNEL32$CreateFileA
#define CloseHandle KERNEL32$CloseHandle
#define GetFileTime KERNEL32$GetFileTime
#define sscanf_s MSVCRT$sscanf_s
#define GetLastError KERNEL32$GetLastError